AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  AvengerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:  
      LayerName: AvengerLayer
      ContentUri: 'python/'
      CompatibleRuntimes:    
        - python3.6  
      RetentionPolicy: Delete
Outputs:
  AvengerLayer:
    Value: !Ref AvengerLayer
    Description: Layer dependencies
