AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  BucketFiles:
    Type: String
  DBUsername:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
  APIKey:
    Type: String

Resources:
  VPCAvengers:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3-us-west-2.amazonaws.com/${BucketFiles}/templates/vpc-template-export.yaml'       

  LayerAvenger:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3-us-west-2.amazonaws.com/${BucketFiles}/templates/layer-template-export.yaml'       
  
  DBAvengers:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3-us-west-2.amazonaws.com/${BucketFiles}/templates/db-template-export.yaml'
      Parameters:
        PublicSubnet1: !Sub ${VPCAvengers.Outputs.PublicSubnet1}
        PublicSubnet2: !Sub ${VPCAvengers.Outputs.PublicSubnet2}
        SecurityGroup: !Sub ${VPCAvengers.Outputs.IngressSecurityGroup}
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword        
        LayerDependenciesArn: !Sub ${LayerAvenger.Outputs.AvengerLayer}

  DBDynamo:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3-us-west-2.amazonaws.com/${BucketFiles}/templates/dynamo-template-export.yaml'      

  APIAvengers:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3-us-west-2.amazonaws.com/${BucketFiles}/templates/api-template-export.yaml'
      Parameters:
        LayerDependenciesArn: !Sub ${LayerAvenger.Outputs.AvengerLayer}        
        DynamoDBTableCreators: !Sub ${DBDynamo.Outputs.DynamoCreators}        
        DynamoDBTablePartners: !Sub ${DBDynamo.Outputs.DynamoCPartners}        

  ETLAvengers:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3-us-west-2.amazonaws.com/${BucketFiles}/templates/etl-template-export.yaml'
      Parameters:
        LayerDependenciesArn: !Sub ${LayerAvenger.Outputs.AvengerLayer}
        BucketFiles: !Ref BucketFiles      
        DynamoDBTableCreators: !Sub ${DBDynamo.Outputs.DynamoCreators}        
        DynamoDBTablePartners: !Sub ${DBDynamo.Outputs.DynamoCPartners}       
        RDSHostname: !Sub ${DBAvengers.Outputs.RDSCluster}
        RDSPort: "5432"
        RDSUsername: !Ref DBUsername
        RDSDBName: avengers
        RDSPassword: !Ref DBPassword
        APIKEY: !Ref APIKey
        PublicSubnet1: !Sub ${VPCAvengers.Outputs.PublicSubnet1}
        PublicSubnet2: !Sub ${VPCAvengers.Outputs.PublicSubnet2}
        SecurityGroup: !Sub ${VPCAvengers.Outputs.IngressSecurityGroup}
        

Outputs:
  ETLAvengers:
    Value: !Sub ${ETLAvengers.Outputs.SFETLArn}
